/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-06 12:13:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._02Join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Join3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>자료실 게시판</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("  font-family:\"Raleway\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form {\r\n");
      out.write("  position:relative;\r\n");
      out.write("  top:0;\r\n");
      out.write("  left:0;\r\n");
      out.write("  margin-top:56px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".form .form-header {\r\n");
      out.write("  height:30px;\r\n");
      out.write("  display:flex;\r\n");
      out.write("  align-items:center;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form .form-header .show-signup {\r\n");
      out.write("  width:calc(100%);\r\n");
      out.write("  color:#f1575b;\r\n");
      out.write("  font-size:20px;\r\n");
      out.write("  font-weight:700;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".form .form-elements {\r\n");
      out.write("  margin-top:15px;\r\n");
      out.write("  width:650px;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".form .form-elements .input {\r\n");
      out.write("  font-size:14px;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  height: 30px;\r\n");
      out.write("  margin-top: 5px;\r\n");
      out.write("  margin:0 auto;\r\n");
      out.write("  padding : 2px 10px;\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("  box-sizing:border-box;\r\n");
      out.write("  border:none;\r\n");
      out.write("  background:#ffeaea;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#idchk, #Mpb, #emailchk, #kakaochk {\r\n");
      out.write("	line-height:30px;\r\n");
      out.write("	margin-left:590px;\r\n");
      out.write("	margin-top:5px;\r\n");
      out.write("	padding:0;\r\n");
      out.write("	width : 60px;\r\n");
      out.write("	font-size:12px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write(".form .form-elements button {\r\n");
      out.write("  \r\n");
      out.write("  font-size:14px;\r\n");
      out.write("  font-weight:600;\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("  background:#f1575b;\r\n");
      out.write("  color:#f5f5f5;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("  border:none;\r\n");
      out.write("  outline:none;\r\n");
      out.write("}\r\n");
      out.write(".form-element {\r\n");
      out.write("	margin-top:10px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".form-check-inline {\r\n");
      out.write("	margin-top:10px;\r\n");
      out.write("}\r\n");
      out.write("#Join1{\r\n");
      out.write("	display:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   function validateForm(form) { //   필수 항목 입력 확인\r\n");
      out.write("      if (form.in_height.value == \"\") {    		\r\n");
      out.write("   			alert(\"키를 입력하지 않았습니다.\");\r\n");
      out.write("   			form.in_height.focus();\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("      if (form.in_style.value == \"\") {    		\r\n");
      out.write(" 			alert(\"체형을 입력하지 않았습니다.\");\r\n");
      out.write(" 			return false;\r\n");
      out.write(" 		}\r\n");
      out.write("   		if(form.in_edu.value==\"\"){\r\n");
      out.write("   			alert(\"학력을 입력하지 않았습니다.\"); \r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("\r\n");
      out.write("   		if(form.in_rlg.value==\"\"){\r\n");
      out.write("   			alert(\"종교를 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_drunk.value==\"\"){\r\n");
      out.write("   			alert(\"음주여부를 입력하지 않았습니다.\");  \r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_smoke.value==\"\"){\r\n");
      out.write("   			alert(\"흡연여부를 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_char.value==\"\"){\r\n");
      out.write("   			alert(\"성격을 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_mbti.value==\"\"){\r\n");
      out.write("   			alert(\"mbti를 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_hobby.value==\"\"){\r\n");
      out.write("   			alert(\"취미를 입력하지 않았습니다.\");\r\n");
      out.write("   			form.in_hobby.focus();\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_job.value==\"\"){\r\n");
      out.write("   			alert(\"직업을 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_haspet.value==\"\"){\r\n");
      out.write("   			alert(\"반려동물 여부를 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("		}\r\n");
      out.write("   		if(form.in_opic.value==\"\"){\r\n");
      out.write("   			alert(\"사진을 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("		}\r\n");
      out.write("   		if(form.in_ovoice.value==\"\"){\r\n");
      out.write("   			alert(\"목소리를 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("		}\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("    <div class=\"form signup\" class=\"p-3 mb-2 bg-secondary text-white\">\r\n");
      out.write("	<div class=\"form-header\">\r\n");
      out.write("    	<h1 class=\"show-signup\" align=\"center\">Sign Up</h1>\r\n");
      out.write("  	</div>\r\n");
      out.write("  	<form name=\"writeFrm2\" method=\"post\" action=\"../controller/Join.do\" >\r\n");
      out.write("		<input type=\"hidden\" name=\"ME_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.ME_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("		<input type=\"hidden\" name=\"ME_PASS\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.ME_PASS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("		<input type=\"hidden\" name=\"ME_NAME\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.ME_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("		<input type=\"hidden\" name=\"ME_BIRTH\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.ME_BIRTH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("		<input type=\"hidden\" name=\"ME_SEX\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.ME_SEX}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("		<input type=\"hidden\" name=\"ME_AGE\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.ME_AGE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("		<input type=\"hidden\" name=\"ME_PHONE\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.ME_PHONE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("		<input type=\"hidden\" name=\"ME_EMAIL\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.ME_EMAIL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("		<input type=\"hidden\" name=\"ME_KAKAO\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.ME_KAKAO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("		<input type=\"hidden\" name=\"RE_NUM\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.RE_NUM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("		<button type=\"submit\" class=\"Join\" id=\"Join1\">회원가입1제출</button>\r\n");
      out.write("	</form>\r\n");
      out.write("  	\r\n");
      out.write("	<form name=\"myFrm\" method=\"post\" enctype=\"multipart/form-data\" \r\n");
      out.write("	action=\"../controller/Join2.do\" onsubmit=\"return validateForm(this);\" >\r\n");
      out.write("		<div align=\"center\" class=\"form-elements\">\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form-element\" style=\"width:300px;justify-content: center;\"> \r\n");
      out.write("				<input class=\"input\" type=\"text\" name=\"in_height\" placeholder=\"키\" style=\"margin:0; \"/>cm\r\n");
      out.write("			</div>\r\n");
      out.write("			<br/>\r\n");
      out.write("			<div class=\"form-element\">체형:\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_style\" id=\"slan\" value=\"슬랜더\"/> 슬랜더				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_style\" id=\"aver\" value=\"보통\"/> 보통				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_style\" id=\"musc\" value=\"근육\"/> 근육				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_style\" id=\"plu\" value=\"통통\"/> 통통\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_style\" id=\"over\" value=\"과체중\"/> 과체중				\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<div class=\"form-element\">\r\n");
      out.write("			최종학력:\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_edu\" id=\"mi\" value=\"중졸이하\"/>중졸이하 				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_edu\" id=\"hi\" value=\"고졸\"/>고졸 				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_edu\" id=\"un\" value=\"대졸\"/>대졸				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_edu\" id=\"gr\" value=\"대학원이상\"/>대학원이상 				\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<div class=\"form-element\">종교:	\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_rlg\" id=\"cath\" value=\"천주교\" /> 천주교				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_rlg\" id=\"chri\" value=\"기독교\" /> 기독교				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_rlg\" id=\"budd\" value=\"불교\" /> 불교				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_rlg\" id=\"Hin\" value=\"힌두교\" /> 힌두교 				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_rlg\" id=\"Isl\" value=\"이슬람교\" /> 이슬람교 			\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_rlg\" id=\"reli\" value=\"무교\" /> 무교				\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>	\r\n");
      out.write("			<hr/>\r\n");
      out.write("			<div class=\"form-element\" style=\"justify-content: center;\">음주:\r\n");
      out.write("				<div style=\"display: flex; width: 200px; justify-content: space-evenly;\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"radio\" name=\"in_drunk\" id=\"yes\" value=\"O\"/> O 				\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"radio\" name=\"in_drunk\" id=\"no\" value=\"X\" /> X 			\r\n");
      out.write("					</div>			\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr/>\r\n");
      out.write("		    <div class=\"form-element\" style=\"justify-content: center;\">흡연:\r\n");
      out.write("		    	<div style=\"display: flex; width: 200px; justify-content: space-evenly;\">\r\n");
      out.write("		    		<div>\r\n");
      out.write("						<input type=\"radio\" name=\"in_smoke\" id=\"o\" value=\"O\" /> O 		    		\r\n");
      out.write("		    		</div>\r\n");
      out.write("		    		<div>\r\n");
      out.write("						<input type=\"radio\" name=\"in_smoke\" id=\"x\" value=\"X\" /> X	    		\r\n");
      out.write("		    		</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<div class=\"form-element\" style=\"justify-content: center;\">성격:\r\n");
      out.write("				<div style=\"display: flex; width: 200px; justify-content: space-evenly;\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"radio\" name=\"in_char\" id=\"ex\" value=\"외향적\" /> 외향적 					\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"radio\" name=\"in_char\" id=\"in\" value=\"내향적\" /> 내향적					\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr/>\r\n");
      out.write("			<div class=\"form-element\">MBTI:\r\n");
      out.write("				<div style=\"display: flex; width: 450px; flex-direction: column;\">\r\n");
      out.write("					<div style=\"display: flex; width: 100%; justify-content: space-between;\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"istj\" value=\"ISTJ\" />ISTJ\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"istp\" value=\"ISTP\" />ISTP					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"isfj\" value=\"ISFJ\" />ISFJ					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"isfp\" value=\"ISFP\" />ISFP					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"intj\" value=\"INTJ\" />INTJ					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"intp\" value=\"INTP\" />INTP					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"infj\" value=\"INFJ\" />INFJ					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"infp\" value=\"INFP\" />INFP									\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<hr/>\r\n");
      out.write("					<div style=\"display: flex; width: 100%; justify-content: space-between;\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"estj\" value=\"ESTJ\" />ESTJ					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"estp\" value=\"ESTP\" />ESTP					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"esfj\" value=\"ESFJ\" />ESFJ					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"esfp\" value=\"ESFP\" />ESFP					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"entj\" value=\"ENTJ\" />ENTJ					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"entp\" value=\"ENTP\" />ENTP					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"enfj\" value=\"ENFJ\" />ENFJ					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"in_mbti\" id=\"enfp\" value=\"ENFP\" />ENFP									\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr/>\r\n");
      out.write("			<div class=\"form-element\">\r\n");
      out.write("				<input class=\"input\" placeholder=\"취미\" type=\"text\" name=\"in_hobby\"  />\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr/>\r\n");
      out.write("			<div class=\"form-element\">직업:\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_job\" id=\"emp\" value=\"회사원\" />회사원				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_job\" id=\"civil\" value=\"공무원\" />공무원				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_job\" id=\"free\" value=\"프리랜서\" />프리랜서				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_job\" id=\"enter\" value=\"예체능\" />예체능				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_job\" id=\"serv\" value=\"군인\" />군인				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_job\" id=\"educ\" value=\"교육\" />교육				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_job\" id=\"med\" value=\"의료\" />의료				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"radio\" name=\"in_job\" id=\"gold\" value=\"금수저\" />금수저					\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("				 	<input type=\"radio\" name=\"in_job\" id=\"njob\" value=\"무직\" />무직				\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("			 		<input type=\"radio\" name=\"in_job\" id=\"the\" value=\"그 외\" />그 외				\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr/>\r\n");
      out.write("			<div class=\"form-element\" style=\"justify-content: center;\">반려동물유무:\r\n");
      out.write("				<div style=\"display: flex; width: 200px; justify-content: space-evenly;\">\r\n");
      out.write("					<div>\r\n");
      out.write("				 		<input type=\"radio\" name=\"in_haspet\" id=\"po\" value=\"유\" />O				\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("				 		<input type=\"radio\" name=\"in_haspet\" id=\"px\" value=\"무\" />X				\r\n");
      out.write("					</div>			\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr/>\r\n");
      out.write("			<div class=\"form-element\">사진파일 :\r\n");
      out.write("		 	 <input class=\"filebtn\" type=\"file\" name=\"in_opic\"  />\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr/>\r\n");
      out.write("			<div class=\"form-element\">목소리파일 :	\r\n");
      out.write("			  	<input class=\"filebtn\" type=\"file\" name=\"in_ovoice\"  />\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr/>\r\n");
      out.write("			  	<button type=\"submit\" class=\"Join\">회원가입 완료</button>\r\n");
      out.write("			  	<button type=\"reset\" >다시시작</button>						\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>   \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
