/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-06 12:46:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._01MainPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProjectMidResult/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1667554890000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1667736724323L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--     팝업설정 -->\r\n");
      out.write(" ");

    String popupMode="on"; // 팝업창 띄우기 
 
    Cookie[] cookie = request.getCookies(); // 쿠키 생성
    if(cookie!=null){
       for(Cookie ck:cookie){
          String ckName=ck.getName();
          if(ckName.equals("PopupMode")){
             popupMode = ck.getValue();
          }
       }
    }
    
      out.write("   \r\n");
      out.write("<!--     팝업 설정  -->\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Main Home Page</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//마우스 하트\r\n");
      out.write("//<![CDATA[\r\n");
      out.write("var colours=new Array('#f00', '#f06', '#f0f', '#f6f', '#f39', '#f9c'); // colours of the hearts\r\n");
      out.write("var minisize=16; // smallest size of hearts in pixels\r\n");
      out.write("var maxisize=28; // biggest size of hearts in pixels\r\n");
      out.write("var hearts=66; // maximum number of hearts on screen\r\n");
      out.write("var over_or_under=\"over\"; // set to \"over\" for hearts to always be on top, or \"under\" to allow them to float behind other objects\r\n");
      out.write("\r\n");
      out.write("/*****************************\r\n");
      out.write("*JavaScript Love Heart Cursor*\r\n");
      out.write("*  (c)2013+ mf2fm web-design *\r\n");
      out.write("*   http://www.mf2fm.com/rv  *\r\n");
      out.write("*  DON'T EDIT BELOW THIS BOX *\r\n");
      out.write("*****************************/\r\n");
      out.write("var x=ox=400;\r\n");
      out.write("var y=oy=300;\r\n");
      out.write("var swide=800;\r\n");
      out.write("var shigh=600;\r\n");
      out.write("var sleft=sdown=0;\r\n");
      out.write("var herz=new Array();\r\n");
      out.write("var herzx=new Array();\r\n");
      out.write("var herzy=new Array();\r\n");
      out.write("var herzs=new Array();\r\n");
      out.write("var kiss=false;\r\n");
      out.write("\r\n");
      out.write("if (typeof('addRVLoadEvent')!='function') function addRVLoadEvent(funky) {\r\n");
      out.write("var oldonload=window.onload;\r\n");
      out.write("if (typeof(oldonload)!='function') window.onload=funky;\r\n");
      out.write("else window.onload=function() {\r\n");
      out.write(" if (oldonload) oldonload();\r\n");
      out.write(" funky();\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("addRVLoadEvent(mwah);\r\n");
      out.write("\r\n");
      out.write("function mwah() { if (document.getElementById) {\r\n");
      out.write("var i, heart;\r\n");
      out.write("for (i=0; i<hearts; i++) {\r\n");
      out.write(" heart=createDiv(\"auto\", \"auto\");\r\n");
      out.write(" heart.style.visibility=\"hidden\";\r\n");
      out.write("	heart.style.zIndex=(over_or_under==\"over\")?\"1001\":\"0\";\r\n");
      out.write(" heart.style.color=colours[i%colours.length];\r\n");
      out.write("	heart.style.pointerEvents=\"none\";\r\n");
      out.write(" if (navigator.appName==\"Microsoft Internet Explorer\") heart.style.filter=\"alpha(opacity=75)\";\r\n");
      out.write(" else heart.style.opacity=0.75;\r\n");
      out.write(" heart.appendChild(document.createTextNode(String.fromCharCode(9829)));\r\n");
      out.write(" document.body.appendChild(heart);\r\n");
      out.write(" herz[i]=heart;\r\n");
      out.write("	herzy[i]=false;\r\n");
      out.write("}\r\n");
      out.write("set_scroll();\r\n");
      out.write("set_width();\r\n");
      out.write("herzle();\r\n");
      out.write("}}\r\n");
      out.write("\r\n");
      out.write("function herzle() {\r\n");
      out.write("var c;\r\n");
      out.write("if (Math.abs(x-ox)>1 || Math.abs(y-oy)>1) {\r\n");
      out.write(" ox=x;\r\n");
      out.write(" oy=y;\r\n");
      out.write(" for (c=0; c<hearts; c++) if (herzy[c]===false) {\r\n");
      out.write("	  herz[c].firstChild.nodeValue=String.fromCharCode(9829);\r\n");
      out.write("   herz[c].style.left=(herzx[c]=x-minisize/2)+\"px\";\r\n");
      out.write("   herz[c].style.top=(herzy[c]=y-minisize)+\"px\";\r\n");
      out.write("   herz[c].style.fontSize=minisize+\"px\";\r\n");
      out.write("	  herz[c].style.fontWeight='normal';\r\n");
      out.write("   herz[c].style.visibility='visible';\r\n");
      out.write("   herzs[c]=minisize;\r\n");
      out.write("   break;\r\n");
      out.write(" }\r\n");
      out.write("}\r\n");
      out.write("for (c=0; c<hearts; c++) if (herzy[c]!==false) blow_me_a_kiss(c);\r\n");
      out.write("setTimeout(\"herzle()\", 40);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.onmousedown=pucker;\r\n");
      out.write("document.onmouseup=function(){clearTimeout(kiss);};\r\n");
      out.write("\r\n");
      out.write("function pucker() {\r\n");
      out.write("ox=-1;\r\n");
      out.write("oy=-1;\r\n");
      out.write("kiss=setTimeout('pucker()', 100);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function blow_me_a_kiss(i) {\r\n");
      out.write("herzy[i]-=herzs[i]/minisize+i%2;\r\n");
      out.write("herzx[i]+=(i%5-2)/5;\r\n");
      out.write("if (herzy[i]<sdown-herzs[i] || herzx[i]<sleft-herzs[i] || herzx[i]>sleft+swide-herzs[i]) {\r\n");
      out.write(" herz[i].style.visibility=\"hidden\";\r\n");
      out.write(" herzy[i]=false;\r\n");
      out.write("}\r\n");
      out.write("else if (herzs[i]>minisize+2 && Math.random()<.5/hearts) break_my_heart(i);\r\n");
      out.write("else {\r\n");
      out.write(" if (Math.random()<maxisize/herzy[i] && herzs[i]<maxisize) herz[i].style.fontSize=(++herzs[i])+\"px\";\r\n");
      out.write(" herz[i].style.top=herzy[i]+\"px\";\r\n");
      out.write(" herz[i].style.left=herzx[i]+\"px\";\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function break_my_heart(i) {\r\n");
      out.write("var t;\r\n");
      out.write("herz[i].firstChild.nodeValue=String.fromCharCode(9676);\r\n");
      out.write("herz[i].style.fontWeight='bold';\r\n");
      out.write("herzy[i]=false;\r\n");
      out.write("for (t=herzs[i]; t<=maxisize; t++) setTimeout('herz['+i+'].style.fontSize=\"'+t+'px\"', 60*(t-herzs[i]));\r\n");
      out.write("setTimeout('herz['+i+'].style.visibility=\"hidden\";', 60*(t-herzs[i]));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.onmousemove=mouse;\r\n");
      out.write("function mouse(e) {\r\n");
      out.write("if (e) {\r\n");
      out.write(" y=e.pageY;\r\n");
      out.write(" x=e.pageX;\r\n");
      out.write("}\r\n");
      out.write("else {\r\n");
      out.write(" set_scroll();\r\n");
      out.write(" y=event.y+sdown;\r\n");
      out.write(" x=event.x+sleft;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("window.onresize=set_width;\r\n");
      out.write("function set_width() {\r\n");
      out.write("var sw_min=999999;\r\n");
      out.write("var sh_min=999999;\r\n");
      out.write("if (document.documentElement && document.documentElement.clientWidth) {\r\n");
      out.write(" if (document.documentElement.clientWidth>0) sw_min=document.documentElement.clientWidth;\r\n");
      out.write(" if (document.documentElement.clientHeight>0) sh_min=document.documentElement.clientHeight;\r\n");
      out.write("}\r\n");
      out.write("if (typeof(self.innerWidth)=='number' && self.innerWidth) {\r\n");
      out.write(" if (self.innerWidth>0 && self.innerWidth<sw_min) sw_min=self.innerWidth;\r\n");
      out.write(" if (self.innerHeight>0 && self.innerHeight<sh_min) sh_min=self.innerHeight;\r\n");
      out.write("}\r\n");
      out.write("if (document.body.clientWidth) {\r\n");
      out.write(" if (document.body.clientWidth>0 && document.body.clientWidth<sw_min) sw_min=document.body.clientWidth;\r\n");
      out.write(" if (document.body.clientHeight>0 && document.body.clientHeight<sh_min) sh_min=document.body.clientHeight;\r\n");
      out.write("}\r\n");
      out.write("if (sw_min==999999 || sh_min==999999) {\r\n");
      out.write(" sw_min=800;\r\n");
      out.write(" sh_min=600;\r\n");
      out.write("}\r\n");
      out.write("swide=sw_min;\r\n");
      out.write("shigh=sh_min;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("window.onscroll=set_scroll;\r\n");
      out.write("function set_scroll() {\r\n");
      out.write("if (typeof(self.pageYOffset)=='number') {\r\n");
      out.write(" sdown=self.pageYOffset;\r\n");
      out.write(" sleft=self.pageXOffset;\r\n");
      out.write("}\r\n");
      out.write("else if (document.body && (document.body.scrollTop || document.body.scrollLeft)) {\r\n");
      out.write(" sdown=document.body.scrollTop;\r\n");
      out.write(" sleft=document.body.scrollLeft;\r\n");
      out.write("}\r\n");
      out.write("else if (document.documentElement && (document.documentElement.scrollTop || document.documentElement.scrollLeft)) {\r\n");
      out.write(" sleft=document.documentElement.scrollLeft;\r\n");
      out.write(" sdown=document.documentElement.scrollTop;\r\n");
      out.write("}\r\n");
      out.write("else {\r\n");
      out.write(" sdown=0;\r\n");
      out.write(" sleft=0;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function createDiv(height, width) {\r\n");
      out.write("var div=document.createElement(\"div\");\r\n");
      out.write("div.style.position=\"absolute\";\r\n");
      out.write("div.style.height=height;\r\n");
      out.write("div.style.width=width;\r\n");
      out.write("div.style.overflow=\"hidden\";\r\n");
      out.write("div.style.backgroundColor=\"transparent\";\r\n");
      out.write("return (div);\r\n");
      out.write("}\r\n");
      out.write("//]]>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\r\n");
      out.write(" <!-- 메인페이지 스타일 -->\r\n");
      out.write(" <style>\r\n");
      out.write("	@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap');\r\n");
      out.write("	@import url('https://fonts.googleapis.com/css2?family=Jua&display=swap');\r\n");
      out.write("\r\n");
      out.write(" 	\r\n");
      out.write(" 	.reviewmain{\r\n");
      out.write(" 		background: linear-gradient(#ead7da, #ffc3bf, #ffbfc0, #ffbfc5, #ffbfca);\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: auto;\r\n");
      out.write("		padding: 5em 10em;\r\n");
      out.write("	}\r\n");
      out.write("	.membermain{\r\n");
      out.write("		border: 1px solid black;\r\n");
      out.write("		background: linear-gradient(#E16A9D,#E6749D,#F479DF, #FFB0D9, #F4B6D9);\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: auto;\r\n");
      out.write("		padding: 5em 10em;\r\n");
      out.write("	}\r\n");
      out.write("	.membermain>div{\r\n");
      out.write("	    display: inline-block;		\r\n");
      out.write("		\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		color: black;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#gen1{\r\n");
      out.write("		font-family: 'Jua', sans-serif;\r\n");
      out.write("		color: \r\n");
      out.write("		border: 3px solid white;;\r\n");
      out.write("		background: linear-gradient(white,#FFBEC3);\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("		background-size: inherit;\r\n");
      out.write("		margin-bottom: 50px;\r\n");
      out.write("		width:30%;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		margin-left: 475px;\r\n");
      out.write("	}\r\n");
      out.write("	#gen2{\r\n");
      out.write("		font-family: 'Jua', sans-serif;\r\n");
      out.write("		font-size: 40px;\r\n");
      out.write("		background: linear-gradient(white,#FFBEC3);\r\n");
      out.write("		border-radius: 15px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	:root {\r\n");
      out.write("		  --level-one: translateZ(3rem);\r\n");
      out.write("		  --level-two: translateZ(6rem);\r\n");
      out.write("		  --level-three: translateZ(9rem);\r\n");
      out.write("		  \r\n");
      out.write("		  --fw-normal: 400;\r\n");
      out.write("		  --fw-bold: 700;\r\n");
      out.write("		  \r\n");
      out.write("		  --clr: #b7c9e5;\r\n");
      out.write("		}	\r\n");
      out.write("	\r\n");
      out.write("		.card, .card::before, .card::after {\r\n");
      out.write("			box-sizing: border-box;\r\n");
      out.write("			margin: 0;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		.card {\r\n");
      out.write("			width: 400px;\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		.card__content {\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			position: relative;\r\n");
      out.write("			padding: 15em 5em;\r\n");
      out.write("			transition: transform 1s;\r\n");
      out.write("			transform-style: preserve-3d;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.card__front,\r\n");
      out.write("		.card__back {\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			top: 0;\r\n");
      out.write("			bottom: 0;\r\n");
      out.write("			left: 0;\r\n");
      out.write("			right: 0;\r\n");
      out.write("			padding: 5em 3em;\r\n");
      out.write("			backface-visibility: hidden;\r\n");
      out.write("			transform-style: preserve-3d;\r\n");
      out.write("			align-content: center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.card__title {\r\n");
      out.write("			font-size: 3rem;\r\n");
      out.write("			transform: var(--level-three);\r\n");
      out.write("			order: 2;\r\n");
      out.write("			text-transform: uppercase;			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		.card:hover .card__content {\r\n");
      out.write("			transform: rotateX(.5turn);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.card__front {\r\n");
      out.write("			padding-top: 10em;\r\n");
      out.write("			background-color: var(--clr);\r\n");
      out.write("			background-size: 100% 100%;\r\n");
      out.write("			background-blend-mode: overlay;\r\n");
      out.write("			color: #333;\r\n");
      out.write("			background-position:center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.card__back {\r\n");
      out.write("			transform: rotateX(.5turn);\r\n");
      out.write("			background: Azure;\r\n");
      out.write("			color: var(--clr);\r\n");
      out.write("			overflow: hidden;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		.card__body {\r\n");
      out.write("			transform: var(--level-two);\r\n");
      out.write("  			font-weight: var(fw-normal);\r\n");
      out.write("			font-size: 1.5rem;\r\n");
      out.write("			line-height: 1.6;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.backfont:hover {\r\n");
      out.write("			color: pink;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.card__subtitle {\r\n");
      out.write("			transform: var(--level-two);\r\n");
      out.write("  			text-transform: uppercase;\r\n");
      out.write("			letter-spacing: 4px;\r\n");
      out.write("			font-size: .75em;\r\n");
      out.write("			font-weight: var(--fw-bold);\r\n");
      out.write("			opacity: .7;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		.card__front::before {\r\n");
      out.write("		  content: '';\r\n");
      out.write("		  position: absolute;\r\n");
      out.write("		  --spacer: 1em;\r\n");
      out.write("		  top: var(--spacer);\r\n");
      out.write("		  bottom: var(--spacer);\r\n");
      out.write("		  left: var(--spacer);\r\n");
      out.write("		  right: var(--spacer);\r\n");
      out.write("		  border: 3px solid currentColor;\r\n");
      out.write("		  transform: var(--level-one);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#gen{\r\n");
      out.write("			margin-left: 280px;\r\n");
      out.write(" 			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#mat{				\r\n");
      out.write("			/* position:fixed;  */\r\n");
      out.write("		   	float: right;\r\n");
      out.write("	  		margin-right: 280px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.pie-chart{\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		.pie-chart {\r\n");
      out.write("		  position: relative;\r\n");
      out.write("		  display:inline-block;\r\n");
      out.write("		  width: 280px;\r\n");
      out.write("		  height: 280px;\r\n");
      out.write("		  border-radius: 50%;\r\n");
      out.write("		  transition: 0.3s;\r\n");
      out.write("		}\r\n");
      out.write("		span.center{\r\n");
      out.write("		  background: #fff;\r\n");
      out.write("		  display : block;\r\n");
      out.write("		  position: absolute;\r\n");
      out.write("		  top:50%; left:50%;\r\n");
      out.write("		  width:140px; height:140px;\r\n");
      out.write("		  border-radius: 50%;\r\n");
      out.write("		  text-align:center; \r\n");
      out.write("		  line-height: 100px;\r\n");
      out.write("		  font-size:40px;\r\n");
      out.write("		  transform: translate(-50%, -50%);\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("		.pie-chart1{\r\n");
      out.write("		  animation: pie1 0.5s forwards;\r\n");
      out.write("		}\r\n");
      out.write("		@keyframes pie1{\r\n");
      out.write("		  0%{background : conic-gradient(#CD426B 0% 0%, #0A6EFF 0% 100%)}\r\n");
      out.write("		  5%{background : conic-gradient(#CD426B 0% 5%, #0A6EFF 0% 100%)}\r\n");
      out.write("		  10%{background : conic-gradient(#CD426B 0% 10%, #0A6EFF 0% 100%)}\r\n");
      out.write("		  15%{background : conic-gradient(#CD426B 0% 15%, #0A6EFF 0% 100%)}\r\n");
      out.write("		  20%{background : conic-gradient(#CD426B 0% 20%, #0A6EFF 0% 100%)}\r\n");
      out.write("		  25%{background : conic-gradient(#CD426B 0% 25%, #0A6EFF 0% 100%)}\r\n");
      out.write("		  30%{background : conic-gradient(#CD426B 0% 30%, #0A6EFF 0% 100%)}\r\n");
      out.write("		  35%{background : conic-gradient(#CD426B 0% 35%, #0A6EFF 0% 100%)}\r\n");
      out.write("		  40%{background : conic-gradient(#CD426B 0% 40%, #0A6EFF 0% 100%)}\r\n");
      out.write("		  45%{background : conic-gradient(#CD426B 0% 45%, #0A6EFF 0% 100%)}	\r\n");
      out.write("		  100%{background : conic-gradient(#CD426B 0% 50%, #0A6EFF 0% 100%)}\r\n");
      out.write("		}\r\n");
      out.write("		.pie-chart2{\r\n");
      out.write("		 animation: pie2 0.5s forwards;\r\n");
      out.write("		}\r\n");
      out.write("		@keyframes pie2{\r\n");
      out.write("		  0%{background : conic-gradient(#288CFF 0% 0%, #464646 0% 100%)}\r\n");
      out.write("		  6%{background : conic-gradient(#288CFF 0% 5%, #464646 0% 100%)}\r\n");
      out.write("		  12%{background : conic-gradient(#288CFF 0% 10%, #464646 0% 100%)}\r\n");
      out.write("		  18%{background : conic-gradient(#288CFF 0% 15%, #464646 0% 100%)}\r\n");
      out.write("		  25%{background : conic-gradient(#288CFF 0% 20%, #464646 0% 100%)}\r\n");
      out.write("		  33%{background : conic-gradient(#288CFF 0% 25%, #464646 0% 100%)}\r\n");
      out.write("		  38%{background : conic-gradient(#288CFF 0% 30%, #464646 0% 100%)}\r\n");
      out.write("		  44%{background : conic-gradient(#288CFF 0% 35%, #464646 0% 100%)}\r\n");
      out.write("		  50%{background : conic-gradient(#288CFF 0% 40%, #464646 0% 100%)}\r\n");
      out.write("		  56%{background : conic-gradient(#288CFF 0% 44%, #464646 0% 100%)}\r\n");
      out.write("		  62%{background : conic-gradient(#288CFF 0% 52%, #464646 0% 100%)}\r\n");
      out.write("		  68%{background : conic-gradient(#288CFF 0% 60%, #464646 0% 100%)}\r\n");
      out.write("		  75%{background : conic-gradient(#288CFF 0% 69%, #464646 0% 100%)}\r\n");
      out.write("		  82%{background : conic-gradient(#288CFF 0% 76%, #464646 0% 100%)}\r\n");
      out.write("		  88%{background : conic-gradient(#288CFF 0% 81%, #464646 0% 100%)}\r\n");
      out.write("		  94%{background : conic-gradient(#288CFF 0% 87%, #464646 0% 100%)}\r\n");
      out.write("		  100%{background : conic-gradient(#288CFF 0% 93%, #464646 0% 100%)}\r\n");
      out.write("		}\r\n");
      out.write(" </style>\r\n");
      out.write("\r\n");
      out.write("<!-- 팝업 스타일 설정 -->\r\n");
      out.write("<style> \r\n");
      out.write("#popup{\r\n");
      out.write("   position:absolute;top:300px;left:130px;\r\n");
      out.write("   width:270px;height:100px; z-index: 2000;\r\n");
      out.write("	\r\n");
      out.write("   }\r\n");
      out.write("#popup>div{\r\n");
      out.write("	position: relative;\r\n");
      out.write("  background-color:white;top:0px;\r\n");
      out.write("   border: 1px solid gray; padding:10px;color:black; \r\n");
      out.write("	width: 570px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!--     팝업 스타일 설정 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 팝업 제이쿼리 설정     -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.1.min.js\" integrity=\"sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function () {\r\n");
      out.write("   $('#closeBtn').click(function(){\r\n");
      out.write("      $('#popup').hide();\r\n");
      out.write("      var chk =$(\"#inactiveToday:checked\").val();\r\n");
      out.write("      if(chk=='1'){\r\n");
      out.write("         $.ajax({\r\n");
      out.write("            url:'./PopupCookie.jsp',\r\n");
      out.write("            type : 'get',\r\n");
      out.write("            data : {inactive:chk},\r\n");
      out.write("            datatype : 'text',\r\n");
      out.write("            success : function(){\r\n");
      out.write("               if(resData!='')location.reload();\r\n");
      out.write("            }\r\n");
      out.write("         })\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 팝업 제이쿼리 설정 -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 팝업이 나오는 창 -->\r\n");
      out.write("   ");

   if(popupMode.equals("on")){
   
      out.write("\r\n");
      out.write("   <div id=\"popup\">\r\n");
      out.write("        <img alt=\"\" src=\"../img/팝업.png\" width=\"570px\" >\r\n");
      out.write("      <div align=\"right\">\r\n");
      out.write("         <form name=\"popForm\">\r\n");
      out.write("            <input type=\"checkbox\" id=\"inactiveToday\" value=\"1\">\r\n");
      out.write("            하루동안 안 열기\r\n");
      out.write("            <input type=\"button\" value=\"닫기\" id=\"closeBtn\">\r\n");
      out.write("         </form>\r\n");
      out.write("      </div>   \r\n");
      out.write("   </div>\r\n");
      out.write("   ");

   }
   
      out.write("\r\n");
      out.write("<!--  팝업이 나오는 창 -->\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/Top.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"membermain\">\r\n");
      out.write("	<h1 id=\"gen1\">회 원 현 황</h1>\r\n");
      out.write("	<div id=\"gen\">\r\n");
      out.write("		<h2 id=\"gen2\">남녀 성비 비율은?</h2><br/><br/><br/>\r\n");
      out.write("		<div class=\"pie-chart pie-chart1\"><span class=\"center\">50%</span></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"mat\">\r\n");
      out.write("		<h2 id=\"gen2\">매칭 성공 비율은?</h2><br/><br/><br/>\r\n");
      out.write("		<div class=\"pie-chart pie-chart2\"><span class=\"center\">93%</span></div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<section>\r\n");
      out.write("<div class=\"reviewmain\" align=\"center\">\r\n");
      out.write("				");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	   <div class=\"container\"style=\"text-align: center; margin-top: 100px; margin-bottom: 100px; border: 1px solid rgba(0, 0, 0, 0.1);\" >\r\n");
      out.write("    	<div class=\"row\" style=\"margin: 30px;\">\r\n");
      out.write("    		<div class=\"col\">\r\n");
      out.write("		    	<img alt=\"\" src=\"https://assets.website-files.com/61d28aad499f21ae92aa33ed/61e4d89641c3e5b3bc63a8ee_Main-Intro-Background.png\" style=\"width:200px; height: auto;\">\r\n");
      out.write("		    	<p style=\"margin-top: 30px;\">2022 한국 브랜드 <br/>리더 대상</p>\r\n");
      out.write("    		</div>\r\n");
      out.write("    		<div class=\"col\" style=\"margin-top: 40px\">\r\n");
      out.write("		    	<img alt=\"\" src=\"https://dimg.donga.com/ugc/CDB/WOMAN/Article/63/05/8c/72/63058c721c87d2738250.jpg\" style=\"width:200px; height: auto;\">\r\n");
      out.write("    			<p style=\"margin-top: 50px;\">2022 대한민국 고객 만족 <br/>브랜드 대상</p>\r\n");
      out.write("    		</div>\r\n");
      out.write("    		<div class=\"col\">\r\n");
      out.write("		    	<img alt=\"\" src=\"https://pds.joongang.co.kr/news/component/htmlphoto_mmdata/202206/28/ec768f43-b08c-44d0-91a1-7e4e49c502f1.jpg\" style=\"width:200px; height: auto;\">\r\n");
      out.write("    			<p style=\"margin-top: 30px;\">2022 고객 감동 우수 <br/>브랜드 대상</p>\r\n");
      out.write("    		</div>\r\n");
      out.write("    		<div class=\"col\">\r\n");
      out.write("		    	<img alt=\"\" src=\"https://compphoto.incruit.com/2013/05/title_gwpseoul_201352818830.gif\" style=\"width:200px; height: auto;\">\r\n");
      out.write("		    	<p style=\"margin-top: 30px;\">2022 일하기 좋은 우수기업 <br/> 100선 선정</p>\r\n");
      out.write("    		</div>\r\n");
      out.write("    		\r\n");
      out.write("    	</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /01MainPage/MainPage.jsp(511,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty mainReviewLists}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<div class=\"card\" style=\"width: 18rem;\"> 등록된 후기가 없습니다.</div>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<div class=\"row\">\r\n");
          out.write("						");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("						</div>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /01MainPage/MainPage.jsp(516,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/01MainPage/MainPage.jsp(516,6) '${mainReviewLists}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${mainReviewLists}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /01MainPage/MainPage.jsp(516,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      // /01MainPage/MainPage.jsp(516,6) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("stat");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<div class=\"col-lg-4 col-md-6\" style=\"display: table-cell; border-spacing:0px;\" >\r\n");
            out.write("								<div class=\"card\">\r\n");
            out.write("									<div class=\"card__content\">\r\n");
            out.write("										<div class=\"card__front\" \r\n");
            out.write("											style=\"background-image: url(../Storage/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.nfile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\">\r\n");
            out.write("								    		<h3 class=\"card__title\">\r\n");
            out.write("								    			평점:\r\n");
            out.write("												");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("												");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("											</h3>\r\n");
            out.write("									    </div> \r\n");
            out.write("										<div class=\"card__back\">\r\n");
            out.write("									    	<a href=\"/MProject/reviewBoard/reviewView.do?num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"backfont\">\r\n");
            out.write("										    	<p class=\"card__body\">제목: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("											    <p class=\"card__body\">작성자: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.RV_POSTNAME }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("											    <p class=\"card__body\">작성일: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.postdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("										  		<p class=\"card__body\">내용: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("									   		</a>\r\n");
            out.write("										</div>\r\n");
            out.write("									</div>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /01MainPage/MainPage.jsp(524,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.star==4}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("★★★★");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /01MainPage/MainPage.jsp(525,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.star==5}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("★★★★★");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
