/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-04 06:30:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.MainPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("	<style>\r\n");
      out.write("	\r\n");
      out.write("	body {\r\n");
      out.write("  background:#2c2c2c;\r\n");
      out.write("  font-family:\"Raleway\";\r\n");
      out.write("}\r\n");
      out.write(".form {\r\n");
      out.write("  position:absolute;\r\n");
      out.write("  top:50%;\r\n");
      out.write("  left:50%;\r\n");
      out.write("  transform:translate(-50%,-50%);\r\n");
      out.write("  width:300px;\r\n");
      out.write("  height:250px;\r\n");
      out.write("  padding:10px;\r\n");
      out.write("}\r\n");
      out.write(".form .form-header {\r\n");
      out.write("  height:30px;\r\n");
      out.write("  display:flex;\r\n");
      out.write("  align-items:center;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("}\r\n");
      out.write(".form .form-header > div {\r\n");
      out.write("  width:calc(100% / 3);\r\n");
      out.write("  color:#ddd;\r\n");
      out.write("  font-size:18px;\r\n");
      out.write("  font-weight:600;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write(".form.signup .form-header div.show-signup {\r\n");
      out.write("  color:#f1575b;\r\n");
      out.write("}\r\n");
      out.write(".form.signin .form-header div.show-signin {\r\n");
      out.write("  color:#f1575b;\r\n");
      out.write("}\r\n");
      out.write(".form.reset .form-header div.show-reset {\r\n");
      out.write("  color:#f1575b;\r\n");
      out.write("}\r\n");
      out.write(".form .form-elements {\r\n");
      out.write("  margin-top:15px;\r\n");
      out.write("}\r\n");
      out.write(".form .form-elements .form-element {\r\n");
      out.write("  height:50px;\r\n");
      out.write("  opacity:1;\r\n");
      out.write("  overflow:hidden;\r\n");
      out.write("  transition:all 500ms ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".form .form-elements input {\r\n");
      out.write("  width:100%;\r\n");
      out.write("  padding:10px;\r\n");
      out.write("  font-size:16px;\r\n");
      out.write("  margin:5px 0px;\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("  box-sizing:border-box;\r\n");
      out.write("  border:1px solid #222;\r\n");
      out.write("  background:#f5f5f5;\r\n");
      out.write("}\r\n");
      out.write(".form .form-elements button {\r\n");
      out.write("  width:100%;\r\n");
      out.write("  padding:10px;\r\n");
      out.write("  font-size:16px;\r\n");
      out.write("  font-weight:600;\r\n");
      out.write("  margin-top:5px;\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("  background:#f1575b;\r\n");
      out.write("  color:#f5f5f5;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("  border:none;\r\n");
      out.write("  outline:none;\r\n");
      out.write("}\r\n");
      out.write(".form .arrow {\r\n");
      out.write("  position:absolute;\r\n");
      out.write("  top:51px;\r\n");
      out.write("  width:0;\r\n");
      out.write("  height:0;\r\n");
      out.write("  border-left:10px solid transparent;\r\n");
      out.write("  border-right:10px solid transparent;\r\n");
      out.write("  border-bottom:10px solid #f5f5f5;\r\n");
      out.write("}\r\n");
      out.write(".form.signup .arrow {\r\n");
      out.write("  left:calc(calc(100% / 3) / 2);\r\n");
      out.write("}\r\n");
      out.write(".form.signin .arrow {\r\n");
      out.write("  left:calc(calc(100% / 3) + calc(calc(100% / 3) / 2.2)) ;\r\n");
      out.write("}\r\n");
      out.write(".form.reset .arrow {\r\n");
      out.write("  left:calc(calc(calc(100% / 3) * 2) + calc(calc(100% / 3) / 3)) ;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form.signin .form-elements > div:nth-child(3) {\r\n");
      out.write("  height:0px;\r\n");
      out.write("  opacity:0;\r\n");
      out.write("}\r\n");
      out.write(".form.reset .form-elements > div:nth-child(2),\r\n");
      out.write(".form.reset .form-elements > div:nth-child(3) {\r\n");
      out.write("  height:0px;\r\n");
      out.write("  opacity:0;\r\n");
      out.write("}\r\n");
      out.write("	\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"form signup\">\r\n");
      out.write("  <div class=\"form-header\">\r\n");
      out.write("    <div class=\"show-signup\">Sign Up</div>\r\n");
      out.write("    <div class=\"show-signin\">Sign In</div>\r\n");
      out.write("    <div class=\"show-reset\">Reset</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"arrow\"></div>\r\n");
      out.write("  <div class=\"form-elements\">\r\n");
      out.write("    <div class=\"form-element\">\r\n");
      out.write("      <input type=\"text\" placeholder=\"Username\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-element\">\r\n");
      out.write("      <input type=\"password\" placeholder=\"Password\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-element\">\r\n");
      out.write("      <input type=\"password\" placeholder=\"Confirm password\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-element\">\r\n");
      out.write("      <button id=\"submit-btn\">Sign Up</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.1.min.js\" integrity=\"sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	function resetClass(element, classname){\r\n");
      out.write("		  element.classList.remove(classname);\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		document.getElementsByClassName(\"show-signup\")[0].addEventListener(\"click\",function(){\r\n");
      out.write("		  let form = document.getElementsByClassName(\"form\")[0];\r\n");
      out.write("		  resetClass(form, \"signin\");\r\n");
      out.write("		  resetClass(form, \"reset\");\r\n");
      out.write("		  form.classList.add(\"signup\");\r\n");
      out.write("		  document.getElementById(\"submit-btn\").innerText = \"Sign Up\";\r\n");
      out.write("		});\r\n");
      out.write("		document.getElementsByClassName(\"show-signin\")[0].addEventListener(\"click\",function(){\r\n");
      out.write("		  let form = document.getElementsByClassName(\"form\")[0];\r\n");
      out.write("		  resetClass(form, \"signup\");\r\n");
      out.write("		  resetClass(form, \"reset\");\r\n");
      out.write("		  form.classList.add(\"signin\");\r\n");
      out.write("		  document.getElementById(\"submit-btn\").innerText = \"Sign In\";\r\n");
      out.write("		});\r\n");
      out.write("		document.getElementsByClassName(\"show-reset\")[0].addEventListener(\"click\",function(){\r\n");
      out.write("		  let form = document.getElementsByClassName(\"form\")[0];\r\n");
      out.write("		  resetClass(form, \"signup\");\r\n");
      out.write("		  resetClass(form, \"signin\");\r\n");
      out.write("		  form.classList.add(\"reset\");\r\n");
      out.write("		  document.getElementById(\"submit-btn\").innerText = \"Reset password\";\r\n");
      out.write("		});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
