/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-04 00:48:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._02Join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Join2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>자료실 게시판</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/Top.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h1 align=\"center\">[회원가입2]</h1>\r\n");
      out.write("		\r\n");
      out.write("	<form name=\"myFrm\" method=\"post\" enctype=\"multipart/form-data\" \r\n");
      out.write("	action=\"../controller/Join2.do\" onsubmit=\"return validateForm(this);\">\r\n");
      out.write("		\r\n");
      out.write("	키:\r\n");
      out.write("		<input type=\"number\" name=\"in_height\"/>cm\r\n");
      out.write("	<br/>\r\n");
      out.write("	체형:\r\n");
      out.write("		<input type=\"radio\" name=\"in_style\" id=\"slan\" value=\"슬랜더\"/> 슬랜더\r\n");
      out.write("		<input type=\"radio\" name=\"in_style\" id=\"aver\" value=\"보통\"/> 보통\r\n");
      out.write("		<input type=\"radio\" name=\"in_style\" id=\"musc\" value=\"근육\"/> 근육\r\n");
      out.write("		<input type=\"radio\" name=\"in_style\" id=\"plu\" value=\"통통\"/> 통통\r\n");
      out.write("		<input type=\"radio\" name=\"in_style\" id=\"over\" value=\"과체중\"/> 과체중\r\n");
      out.write("	<br/>\r\n");
      out.write("	최종학력:\r\n");
      out.write("		<input type=\"radio\" name=\"in_edu\" id=\"mi\" value=\"중졸이하\"/>중졸이하 \r\n");
      out.write("		<input type=\"radio\" name=\"in_edu\" id=\"hi\" value=\"고졸\"/>고졸 \r\n");
      out.write("		<input type=\"radio\" name=\"in_edu\" id=\"un\" value=\"대졸\"/>대졸 \r\n");
      out.write("		<input type=\"radio\" name=\"in_edu\" id=\"gr\" value=\"대학원이상\"/>대학원이상\r\n");
      out.write("	<br/>\r\n");
      out.write("	종교:	\r\n");
      out.write("		<input type=\"radio\" name=\"in_rlg\" id=\"cath\" value=\"천주교\" /> 천주교\r\n");
      out.write("		<input type=\"radio\" name=\"in_rlg\" id=\"chri\" value=\"기독교\" /> 기독교\r\n");
      out.write("		<input type=\"radio\" name=\"in_rlg\" id=\"budd\" value=\"불교\" /> 불교\r\n");
      out.write("		<input type=\"radio\" name=\"in_rlg\" id=\"Hin\" value=\"힌두교\" /> 힌두교 \r\n");
      out.write("		<input type=\"radio\" name=\"in_rlg\" id=\"Isl\" value=\"이슬람교\" /> 이슬람교 \r\n");
      out.write("		<input type=\"radio\" name=\"in_rlg\" id=\"reli\" value=\"무교\" /> 무교\r\n");
      out.write("		\r\n");
      out.write("	<br/>\r\n");
      out.write("	음주:\r\n");
      out.write("		<input type=\"radio\" name=\"in_drunk\" id=\"yes\" value=\"O\" />O \r\n");
      out.write("		<input type=\"radio\" name=\"in_drunk\" id=\"no\" value=\"X\" />X \r\n");
      out.write("	<br/>\r\n");
      out.write("    흡연:\r\n");
      out.write("		<input type=\"radio\" name=\"in_smoke\" id=\"o\" value=\"O\" />O \r\n");
      out.write("		<input type=\"radio\" name=\"in_smoke\" id=\"x\" value=\"X\" />X <br/>\r\n");
      out.write("	성격\r\n");
      out.write("		<input type=\"radio\" name=\"in_char\" id=\"ex\" value=\"외향적\" />외향적 \r\n");
      out.write("		<input type=\"radio\" name=\"in_char\" id=\"in\" value=\"내향적\" />내향적\r\n");
      out.write("	 <br/>\r\n");
      out.write("	MBTI:\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"istj\" value=\"ISTJ\" />ISTJ\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"istp\" value=\"ISTP\" />ISTP\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"isfj\" value=\"ISFJ\" />ISFJ\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"isfp\" value=\"ISFP\" />ISFP\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"intj\" value=\"INTJ\" />INTJ\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"intp\" value=\"INTP\" />INTP\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"infj\" value=\"INFJ\" />INFJ\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"infp\" value=\"INFP\" />INFP\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"estj\" value=\"ESTJ\" />ESTJ\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"estp\" value=\"ESTP\" />ESTP\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"esfj\" value=\"ESFJ\" />ESFJ\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"esfp\" value=\"ESFP\" />ESFP\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"entj\" value=\"ENTJ\" />ENTJ\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"entp\" value=\"ENTP\" />ENTP\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"enfj\" value=\"ENFJ\" />ENFJ\r\n");
      out.write("		<input type=\"radio\" name=\"in_mbti\" id=\"enfp\" value=\"ENFP\" />ENFP\r\n");
      out.write("	<br/>\r\n");
      out.write("	취미:\r\n");
      out.write("		<input type=\"text\" name=\"in_hobby\"  />\r\n");
      out.write("	<br/>\r\n");
      out.write("	직업:\r\n");
      out.write("		<input type=\"radio\" name=\"in_job\" id=\"emp\" value=\"회사원\" />회사원\r\n");
      out.write("		<input type=\"radio\" name=\"in_job\" id=\"civil\" value=\"공무원\" />공무원\r\n");
      out.write("		<input type=\"radio\" name=\"in_job\" id=\"free\" value=\"프리랜서\" />프리랜서\r\n");
      out.write("		<input type=\"radio\" name=\"in_job\" id=\"enter\" value=\"예체능\" />예체능\r\n");
      out.write("		<input type=\"radio\" name=\"in_job\" id=\"serv\" value=\"군인\" />군인\r\n");
      out.write("		<input type=\"radio\" name=\"in_job\" id=\"educ\" value=\"교육\" />교육\r\n");
      out.write("		<input type=\"radio\" name=\"in_job\" id=\"med\" value=\"의료\" />의료\r\n");
      out.write("		<input type=\"radio\" name=\"in_job\" id=\"gold\" value=\"금수저\" />금수저	\r\n");
      out.write("	 	<input type=\"radio\" name=\"in_job\" id=\"njob\" value=\"무직\" />무직\r\n");
      out.write(" 		<input type=\"radio\" name=\"in_job\" id=\"the\" value=\"그 외\" />그 외\r\n");
      out.write("	<br/>\r\n");
      out.write("	반려동물유무:\r\n");
      out.write(" 		<input type=\"radio\" name=\"in_haspet\" id=\"po\" value=\"유\" />O\r\n");
      out.write(" 		<input type=\"radio\" name=\"in_haspet\" id=\"px\" value=\"무\" />X\r\n");
      out.write("	<br/>\r\n");
      out.write("	사진파일 :\r\n");
      out.write(" 	 <input type=\"file\" name=\"in_opic\"  />\r\n");
      out.write("	<br/>\r\n");
      out.write("	목소리파일 :	\r\n");
      out.write("	  	<input type=\"file\" name=\"in_ovoice\"  />\r\n");
      out.write("	<br/>\r\n");
      out.write("	  	<button type=\"submit\" class=\"Join\">회원가입</button>\r\n");
      out.write("	  	<button type=\"reset\">초기화</button>						\r\n");
      out.write("	</form> \r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("   function validateForm(form) { //   필수 항목 입력 확인\r\n");
      out.write("      if (form.in_height.value == \"\") {    		\r\n");
      out.write("   			alert(\"키를 입력하지 않았습니다.\");\r\n");
      out.write("   			form.in_height.focus();\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("      if (form.in_style.value == \"\") {    		\r\n");
      out.write(" 			alert(\"체형을 입력하지 않았습니다.\");\r\n");
      out.write(" 			return false;\r\n");
      out.write(" 		}\r\n");
      out.write("   		if(form.in_edu.value==\"\"){\r\n");
      out.write("   			alert(\"학력을 입력하지 않았습니다.\"); \r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("\r\n");
      out.write("   		if(form.in_rlg.value==\"\"){\r\n");
      out.write("   			alert(\"종교를 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_drunk.value==\"\"){\r\n");
      out.write("   			alert(\"음주여부를 입력하지 않았습니다.\");  \r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_smoke.value==\"\"){\r\n");
      out.write("   			alert(\"흡연여부를 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_char.value==\"\"){\r\n");
      out.write("   			alert(\"성격을 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_mbti.value==\"\"){\r\n");
      out.write("   			alert(\"mbti를 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_hobby.value==\"\"){\r\n");
      out.write("   			alert(\"취미를 입력하지 않았습니다.\");\r\n");
      out.write("   			form.in_hobby.focus();\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_job.value==\"\"){\r\n");
      out.write("   			alert(\"직업을 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   		if(form.in_haspet.value==\"\"){\r\n");
      out.write("   			alert(\"반려동물 여부를 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("		}\r\n");
      out.write("   		if(form.in_opic.value==\"\"){\r\n");
      out.write("   			alert(\"사진을 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("		}\r\n");
      out.write("   		if(form.in_ovoice.value==\"\"){\r\n");
      out.write("   			alert(\"목소리를 입력하지 않았습니다.\");\r\n");
      out.write("   			return false;\r\n");
      out.write("		}\r\n");
      out.write("		//키 제한\r\n");
      out.write("   		if(form.in_height.value>300){\r\n");
      out.write("   			alert(\"키를 다시 입력 해주세요.\")\r\n");
      out.write("   			form.in_height.focus();\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}//오버 키 제한\r\n");
      out.write("   		if(form.in_height.value<100){\r\n");
      out.write("   			alert(\"키를 다시 체크 해주세요.\")\r\n");
      out.write("   			form.in_height.focus();\r\n");
      out.write("   			return false;\r\n");
      out.write("   		}\r\n");
      out.write("   }\r\n");
      out.write("</script>  \r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
