/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-04 08:45:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.InfoBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class InfoPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");

	request.setCharacterEncoding("UTF-8");

	String name = request.getParameter("name");	
	

      out.write("    \r\n");
      out.write("    	\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("		@import url('https://fonts.googleapis.com/css2?family=Song+Myung&display=swap');\r\n");
      out.write("   \r\n");
      out.write("    ");

    	if(name=="소개") {
    
      out.write("\r\n");
      out.write("    	\r\n");
      out.write("   		#indicator:checked {\r\n");
      out.write("   			background: linear-gradient(130deg, yellow, red);\r\n");
      out.write("   		}\r\n");
      out.write("   		\r\n");
      out.write("    ");

    	} 
    
      out.write("\r\n");
      out.write("    	\r\n");
      out.write("		\r\n");
      out.write("		html, body{height: 100%;}\r\n");
      out.write("		#h2 {font-family: 'Song Myung', serif;margin-top: 100px;letter-spacing:8px;}\r\n");
      out.write("		#h22{\r\n");
      out.write("			font-family: 'Song Myung', serif;\r\n");
      out.write("			margin-top: 20px;\r\n");
      out.write("			margin-left: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		#title{margin-top: 270px;}\r\n");
      out.write("		#p{font-size: 100px;color: black;}\r\n");
      out.write("		#t{color: #6495ED;font-size: 55px;}\r\n");
      out.write("		.part{height: 100%;width: 100%;}\r\n");
      out.write("		.one{background: linear-gradient(50deg, white, pink);\r\n");
      out.write("			width: 900px;height: 700px; \r\n");
      out.write("			text-align: center;\r\n");
      out.write("			margin-top: 100px;\r\n");
      out.write("		}\r\n");
      out.write("		#h2{\r\n");
      out.write("			animation: fadein 3.5s;\r\n");
      out.write("			-webkit-animation: fadein 3.5s;\r\n");
      out.write("		}\r\n");
      out.write("		@keyframes fadein {\r\n");
      out.write("			from {opacity: 0;}		\r\n");
      out.write("			to {opacity: 1;}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.par{background: linear-gradient(50deg, white, pink);}\r\n");
      out.write("		#zero{display: inline-block; \r\n");
      out.write("			font-family: 'Song Myung', serif; font-size: 25px; \r\n");
      out.write("		}\r\n");
      out.write("		#zero1{font-weight: bold;}\r\n");
      out.write("		#zero2{color: #6E6ED7;}\r\n");
      out.write("		#tit{font-size: 50px;color:#FF6E6E;letter-spacing:8px; }\r\n");
      out.write("		#sunset{margin: 150px 200px 180px 120px;\r\n");
      out.write("			width: 600px; height: 500px;\r\n");
      out.write("			border: 3px solid; border-radius: 50%; border-color: white; }\r\n");
      out.write("		\r\n");
      out.write("		#comment3{position: absolute;}\r\n");
      out.write("		.two{background: linear-gradient(50deg, white, pink);}\r\n");
      out.write("		#chapter2{\r\n");
      out.write("			display: inline-block;\r\n");
      out.write("			margin-top: 80px;\r\n");
      out.write("			margin-left: 150px;\r\n");
      out.write("			top:0;\r\n");
      out.write("			font-family: 'Song Myung', serif;\r\n");
      out.write("		}\r\n");
      out.write("		.graph{\r\n");
      out.write("			margin: 100px 50px 70px 5px; \r\n");
      out.write("			height: 700px; width:800px; \r\n");
      out.write("			border: 5px solid #282828;\r\n");
      out.write("			border-radius: 10px;\r\n");
      out.write("			position: relative;\r\n");
      out.write("		}\r\n");
      out.write("		ul>li{\r\n");
      out.write("			font-size: 15px;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("		}\r\n");
      out.write("		#comment3{margin-right: 60px;}\r\n");
      out.write("		.chap2{letter-spacing:10px; font-size: 30px;}\r\n");
      out.write("		.chap22{;font-size: 23px; margin-top: 80px;}\r\n");
      out.write("		.a{background: #FF9696;}\r\n");
      out.write("		.b{background: #F08080;}\r\n");
      out.write("		.c{background: #F56E6E;}\r\n");
      out.write("		.d{background: #F06464;}\r\n");
      out.write("		\r\n");
      out.write("		span:nth-of-type(1){ height:71.2%; left: 50px;}\r\n");
      out.write("		span:nth-of-type(2){ height:63.1%; left: 260px;}\r\n");
      out.write("		span:nth-of-type(3){ height:60.8%; left: 450px;}\r\n");
      out.write("		span:nth-of-type(4){ height:59.6%; left: 640px;}\r\n");
      out.write("		\r\n");
      out.write("		#chapter2 span{\r\n");
      out.write("			font-size: 25px;\r\n");
      out.write("			line-height: 2em;\r\n");
      out.write("			color: black;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			border-radius: 15px;\r\n");
      out.write("			display: inline-block;\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			bottom: 0;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#a1{font-weight: bold; color:#3232FF; font-size: 50px;}\r\n");
      out.write("		\r\n");
      out.write("		#part3{display: inline-block;}	\r\n");
      out.write("		.three{background: linear-gradient(50deg, white, pink);}\r\n");
      out.write("		#couplepic{\r\n");
      out.write("			margin: 50px 200px 180px 120px;\r\n");
      out.write("			width: 700px; height: 500px;\r\n");
      out.write("			border: 3px solid; border-radius: 50%; border-color: #FFFF8C; \r\n");
      out.write("		}\r\n");
      out.write("		#list{text-align:center; margin-top: 150px;}\r\n");
      out.write("		#h3{font-family: 'Song Myung', serif; font-size: 40px;}\r\n");
      out.write("		#p1 {font-family: 'Song Myung', serif;font-size: 25px;}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		.four{background: linear-gradient(50deg, white, pink);}\r\n");
      out.write("		.last{display: inline-block; margin-right: 145px; margin-left: 145px; margin-bottom: 40px;}\r\n");
      out.write("		#stress,#type,#delete{\r\n");
      out.write("			margin-top: 50px;\r\n");
      out.write("			width:330px;\r\n");
      out.write("			height: 300px;\r\n");
      out.write("			border: 3px solid white;\r\n");
      out.write("			border-radius: 15%;	\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#lastd{text-align: center;}\r\n");
      out.write("		#lasth2,#lasta{font-family: 'Song Myung', serif;}\r\n");
      out.write("		#lasth2{font-size: 30px;text-align: center;}\r\n");
      out.write("		#lasta{font-size: 17px;}\r\n");
      out.write("	</style>\r\n");
      out.write("\r\n");
      out.write("	<title>Insert title here</title>\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("	<body>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../Common/Top.jsp", out, false);
      out.write(" \r\n");
      out.write("		\r\n");
      out.write("		<div class=\"list\">\r\n");
      out.write("			<div class=\"parent row\">\r\n");
      out.write("				<div class=\"part one\" id=\"one\">\r\n");
      out.write("					<div id=\"title\">\r\n");
      out.write("					<h2 id=\"h2\">\r\n");
      out.write("						<a id=\"p\">P</a><a id=\"t\">recious</a>       \r\n");
      out.write("						<a id=\"p\">Q</a><a id=\"t\">uality</a> \r\n");
      out.write("						<a id=\"p\">T</a><a id=\"t\">ime</a>\r\n");
      out.write("					</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"part par\" id=\"zero\">\r\n");
      out.write("					<img src=\"./pic/sunset.jpg\" id=\"sunset\">\r\n");
      out.write("					<div id=\"zero\">\r\n");
      out.write("						<div id=\"zero1\">\r\n");
      out.write("						<h2 id=\"tit\">PQT란...</h2> <br/>\r\n");
      out.write("						귀중하고 소중한 시간을 가치있게 보내자는 뜻으로 <br/><br/>\r\n");
      out.write("						서로를 만나 같이를 가치있게 보내자는 의미를 담아 제공하는 페이지입니다. \r\n");
      out.write("						<br/><br/><br/>\r\n");
      out.write("						<p id=\"zero2\">이 페이지는 비혼주의자들을 위한 검증된 싱글 남녀를 위한 1:1 매칭 서비스를 진행하고 있습니다.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"part two\">\r\n");
      out.write("					<div class=\"graph\" id=\"chapter2\">\r\n");
      out.write("						<h1 id=\"h22\">비혼 선호도 조사</h1>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li>경제적 어려움(71.2%)</li>\r\n");
      out.write("							<li>양육비 부담(63.1%)</li>\r\n");
      out.write("							<li>주거비 부담(60.8%)</li>\r\n");
      out.write("							<li>결혼비용 부담(59.6%)</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<span class=\"a\" data-val=\"71.2\">71.2%</span>\r\n");
      out.write("						<span class=\"b\" data-val=\"63.1\">63.1%</span>\r\n");
      out.write("						<span class=\"c\" data-val=\"60.8\">60.8%</span>\r\n");
      out.write("						<span class=\"d\" data-val=\"59.6\">59.6%</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"chapter2\" class=\"service\">\r\n");
      out.write("						<div id=\"comment3\">\r\n");
      out.write("						<h2 class=\"chap2\">왜 <a id=\"a1\">비혼주의자</a>들을 위한 PQT인가?</h2>\r\n");
      out.write("						<p class=\"chap22\">\r\n");
      out.write("						왼쪽 자료를 보시면 아시다시피<br/>\r\n");
      out.write("						현재 비혼주의가 많아지는 이유를 알 수가 있습니다.<br/>\r\n");
      out.write("						본인의 삶, 자녀육성에 대한 부담, 금전적 문제, 폭등하는 집 값<br/> \r\n");
      out.write("						환경적 사회적 원인들 뿐만 아니라 <br/>\r\n");
      out.write("						2020년 조사결과,<br/>\r\n");
      out.write("						53%의 20, 30대의 비혼을 원하는 사람들이 점점 늘어나는 것을 알 수가 있다.\r\n");
      out.write("						</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"part three\" id=\"part3\">\r\n");
      out.write("					<img id=\"couplepic\" src=\"./pic/couple2.jpg\">\r\n");
      out.write("						<div class=\"intro\" id=\"part3\">\r\n");
      out.write("							<div id=\"list\">\r\n");
      out.write("								<h2 id=\"h3\">그런 고객분들을 위해 PQT가 준비했습니다!</h2>\r\n");
      out.write("								</br></br></br>\r\n");
      out.write("								<p id=\"p1\">\r\n");
      out.write("									1. 결혼 생각을 가지지 않는 사람들끼리 편하게 만날 수 있습니다.</br></br>\r\n");
      out.write("									2. 본인의 삶을 충분히 챙기며 만남을 이어갈 수 있습니다.</br></br>\r\n");
      out.write("									3. PQT는 뛰어난 성사율, 실시간으로 검증이 된 사람들을 토대로 진행이 됩니다.</br></br>\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>					\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"part four\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"last\">\r\n");
      out.write("							<img src=\"./pic/stress.jpg\" id=\"stress\"><br/><br/>\r\n");
      out.write("							<h3 id=\"lasth2\">신상 노출 \"NO\"</h3>\r\n");
      out.write("							<br/>\r\n");
      out.write("							<div id=\"lastd\">\r\n");
      out.write("							<a id=\"lasta\">\r\n");
      out.write("								저희 PQT는 신상 노출이 되지않습니다 !<br/>\r\n");
      out.write("								또한 가입이 되지않는 사람을<br/>\r\n");
      out.write("								매칭하며 만남까지 가지는 것은 불가합니다.<br/>\r\n");
      out.write("		\r\n");
      out.write("								프라이버시를 가장 중요하게 생각하기 때문에<br/>\r\n");
      out.write("								무작위로 신상이 노출되지 않습니다.<br/>\r\n");
      out.write("							</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"last\">\r\n");
      out.write("							<img src=\"./pic/type.jpg\" id=\"type\"><br/><br/>\r\n");
      out.write("							<h3 id=\"lasth2\">회원 차별 매칭 \"NO\"</h3>\r\n");
      out.write("							<div id=\"lastd\">\r\n");
      out.write("							<a id=\"lasta\">\r\n");
      out.write("								저희 PQT는 사회적으로<br/>\r\n");
      out.write("								차별화된 매칭 페이지가 아닙니다.<br/>\r\n");
      out.write("								<br/>\r\n");
      out.write("								남성회원 및 여성회원 모두<br/>\r\n");
      out.write("								소중한 저희 회원이며 , 서로가 원하는<br/>\r\n");
      out.write("								이상형에 맞춤 필터를 제공하는 소개팅입니다.<br/>\r\n");
      out.write("							</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"last\">\r\n");
      out.write("							<img src=\"./pic/delete.jpg\" id=\"delete\"><br/><br/>\r\n");
      out.write("							<h3 id=\"lasth2\">비매너 회원 즉시 \"제명\"</h3>\r\n");
      out.write("							<div id=\"lastd\">\r\n");
      out.write("							<a id=\"lasta\">\r\n");
      out.write("								PQT는 신뢰와 매너를 가장 중요시합니다.<br/>\r\n");
      out.write("								<br/>\r\n");
      out.write("								저희 PQT는 회원 차별없이<br/>\r\n");
      out.write("								비매너 언행과 행동이 확인 된 회원 및 <br/>\r\n");
      out.write("								매칭에 의사가 없거나 or 장난으로 가입하신 회원은<br/>\r\n");
      out.write("								블랙리스트로 제명이 됩니다.<br/>\r\n");
      out.write("							</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../Common/Footer.jsp", out, false);
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
