/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-03 07:57:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.prac;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class JoinH_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>자료실 게시판</title>\r\n");
      out.write("<style>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  font-family:\"Raleway\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form {\r\n");
      out.write("  position:relative;\r\n");
      out.write("  top:0;\r\n");
      out.write("  left:0;\r\n");
      out.write("  margin-top:56px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".form .form-header {\r\n");
      out.write("  height:30px;\r\n");
      out.write("  display:flex;\r\n");
      out.write("  align-items:center;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form .form-header .show-signup {\r\n");
      out.write("  width:calc(100%);\r\n");
      out.write("  color:#f1575b;\r\n");
      out.write("  font-size:20px;\r\n");
      out.write("  font-weight:700;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".form .form-elements {\r\n");
      out.write("  margin-top:15px;\r\n");
      out.write("  width:650px;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".form .form-elements input {\r\n");
      out.write("  font-size:14px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 30px;\r\n");
      out.write("  margin-top: 5px;\r\n");
      out.write("  margin:0 auto;\r\n");
      out.write("  padding : 2px 10px;\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("  box-sizing:border-box;\r\n");
      out.write("  border:none;\r\n");
      out.write("  background:#ffeaea;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#idchk, #Mpb, #emailchk, #kakaochk {\r\n");
      out.write("	line-height:30px;\r\n");
      out.write("	margin-left:590px;\r\n");
      out.write("	margin-top:5px;\r\n");
      out.write("	padding:0;\r\n");
      out.write("	width : 60px;\r\n");
      out.write("	font-size:12px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write(".form .form-elements button {\r\n");
      out.write("  \r\n");
      out.write("  font-size:14px;\r\n");
      out.write("  font-weight:600;\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("  background:#f1575b;\r\n");
      out.write("  color:#f5f5f5;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("  border:none;\r\n");
      out.write("  outline:none;\r\n");
      out.write("}\r\n");
      out.write(".form-element {\r\n");
      out.write("	margin-top:10px;\r\n");
      out.write("}\r\n");
      out.write(".form-check-inline {\r\n");
      out.write("	margin-top:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../Common/Top.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   function validateForm(form) { //   필수 항목 입력 확인\r\n");
      out.write("      if (form.ME_ID.value ==\"\") {          \r\n");
      out.write("            alert(\"아이디를 입력하지 않았습니다.\");\r\n");
      out.write("            form.ME_ID.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("      if (form.ME_ID.value == \"\") {          \r\n");
      out.write("          alert(\"아이디를 입력하지 않았습니다.\");\r\n");
      out.write("          form.ME_ID.focus();\r\n");
      out.write("          return false;\r\n");
      out.write("       }\r\n");
      out.write("         if(form.ME_PASS.value==\"\"){\r\n");
      out.write("            alert(\"비밀번호를 입력하지 않았습니다.\");\r\n");
      out.write("            form.ME_PASS.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if(form.ME_PASS.value!= form.ME_PASS2.value){\r\n");
      out.write("            alert(\"비밀번호가 일치하지 않았습니다.\");\r\n");
      out.write("            form.ME_PASS.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("         if(form.ME_PASS2.value==\"\"){\r\n");
      out.write("            alert(\"비밀번호 재확인을 입력하지 않았습니다.\");\r\n");
      out.write("            form.ME_PASS2.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if(form.ME_NAME.value==\"\"){\r\n");
      out.write("            alert(\"이름을 입력하지 않았습니다.\");\r\n");
      out.write("            form.ME_NAME.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if(form.ME_BIRTH.value==\"\"){\r\n");
      out.write("            alert(\"생년원일을 입력하지 않았습니다.\");\r\n");
      out.write("            form.ME_BIRTH.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if(form.ME_BIRTH.value.length>10){\r\n");
      out.write("            alert(\"잘못된 생년월일 입니다.\")\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write(" \r\n");
      out.write("         if(form.ME_SEX.value==\"\"){\r\n");
      out.write("            alert(\"성별을 입력하지 않았습니다.\");\r\n");
      out.write("            form.ME_SEX.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if(form.ME_AGE.value==\"\"){\r\n");
      out.write("            alert(\"나이를 입력하지 않았습니다.\");\r\n");
      out.write("            form.ME_AGE.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if(form.ME_AGE.value<20){\r\n");
      out.write("            alert(\"미성년자입니다.\")\r\n");
      out.write("            form.ME_AGE.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if(form.ME_PHONE.value==\"\"){\r\n");
      out.write("            alert(\"전화번호를 입력하지 않았습니다.\");\r\n");
      out.write("            form.ME_PHONE.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if(form.ME_EMAIL.value==\"\"){\r\n");
      out.write("            alert(\"이메일을 입력하지 않았습니다.\");\r\n");
      out.write("            form.ME_EMAIL.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if(form.ME_KAKAO.value==\"\"){\r\n");
      out.write("            alert(\"카카오 아이디를 입력하지 않았습니다.\");\r\n");
      out.write("            form.ME_KAKAO.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if(form.RE_NUM.value==\"\"){\r\n");
      out.write("            alert(\"지역번호를 입력하지 않았습니다.\");\r\n");
      out.write("            form.RE_NUM.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("      }         \r\n");
      out.write("\r\n");
      out.write("        if(form.idDuplication.value == \"idUncheck\"){\r\n");
      out.write("            alert(\"아이디 중복체크를 해주세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("   }\r\n");
      out.write("      \r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"form signup\" class=\"p-3 mb-2 bg-secondary text-white\">\r\n");
      out.write("	<div class=\"form-header\">\r\n");
      out.write("    	<h1 class=\"show-signup\">Sign Up</h1>\r\n");
      out.write("  	</div>\r\n");
      out.write("\r\n");
      out.write("	<form name=\"writeFrm\" method=\"post\" action=\"../controller/Join.do\"\r\n");
      out.write("	onsubmit = \"return validateForm(this);\" >\r\n");
      out.write("		<div class=\"form-elements\" align=\"center\" >\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form-element\" style=\"position: relative;\">\r\n");
      out.write("				<input type=\"text\" placeholder=\"아이디\"  name=\"ME_ID\" id=\"Idchecks\" />\r\n");
      out.write("				<button type=\"button\" id=\"idchk\" name=\"idcheck\">중복확인</button>\r\n");
      out.write("		      	<font id = \"checkId\" size = \"1\"></font>\r\n");
      out.write("	      	</div>\r\n");
      out.write("	      	\r\n");
      out.write("	      	<div class=\"form-element\">\r\n");
      out.write("				<input type=\"password\" placeholder=\"비밀번호\"  name=\"ME_PASS\" id=\"ME_PASS\" class=\"pw\" />\r\n");
      out.write("	      	</div>\r\n");
      out.write("	      	\r\n");
      out.write("	      	<div class=\"form-element\">\r\n");
      out.write("				<input type=\"password\" placeholder=\"비밀번호확인\"  name=\"ME_PASS2\" id=\"ME_PASS2\" class=\"pw\" />\r\n");
      out.write("				<font id = \"checkPw\" size = \"2\"></font>\r\n");
      out.write("	      	</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form-element\">\r\n");
      out.write("				<input type=\"text\" placeholder=\"이름\"  name=\"ME_NAME\" />\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form-element\">\r\n");
      out.write("				<input type=\"text\" placeholder=\"생년월일\" name=\"ME_BIRTH\" />\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form-check form-check-inline\">\r\n");
      out.write("			  <input class=\"form-check-input\" type=\"radio\" name=\"inlineRadioOptions\" id=\"inlineRadio1\" value=\"option1\" style=\"padding:0;\">\r\n");
      out.write("			  <label class=\"form-check-label\" for=\"inlineRadio1\">남자</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form-check form-check-inline\">\r\n");
      out.write("			  <input class=\"form-check-input\" type=\"radio\" name=\"inlineRadioOptions\" id=\"inlineRadio2\" value=\"option2\" style=\"padding:0;\">\r\n");
      out.write("			  <label class=\"form-check-label\" for=\"inlineRadio2\">여자</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-element\">\r\n");
      out.write("				<input type=\"number\" placeholder=\"나이\"  name=\"ME_AGE\" />\r\n");
      out.write("			</div>   \r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form-element\">\r\n");
      out.write("			<input type=\"tel\" placeholder=\"핸드폰 번호\"  name=\"ME_PHONE\" id=\"Mpv\"/>\r\n");
      out.write("			  	<button type=\"button\" name=\"phonecheck\" id=\"Mpb\">확인</button>\r\n");
      out.write("	      		<font size = \"2\" id = \"Mpf\" ></font>\r\n");
      out.write("	      	</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form-element\">\r\n");
      out.write("			<input type=\"email\" placeholder=\"이메일 주소\"  name=\"ME_EMAIL\" id=\"emailchkv\"  />\r\n");
      out.write("			 	<button type=\"button\" name=\"emailcheck\" id=\"emailchk\">확인</button>\r\n");
      out.write("	      		<font size = \"2\" id = \"emailft\" ></font>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form-element\">\r\n");
      out.write("			 <input type=\"text\" placeholder=\"카카오ID\"  name=\"ME_KAKAO\" id=\"kakaochkv\" />\r\n");
      out.write("				<button type=\"button\" name=\"emailcheck\" id=\"kakaochk\">확인</button>\r\n");
      out.write("	      		<font size = \"2\" id = \"kakaoft\" ></font>\r\n");
      out.write("			</div>\r\n");
      out.write("   \r\n");
      out.write("      <div class=\"form-element\" style=\"background-color:#ffeaea; border-radius: 10px; display: flex; width: 200px; justify-content: space-between;\">\r\n");
      out.write("      지역번호<select name=\"RE_NUM\" id=\"renum\" style=\"background-color:white; border-radius: 10px; \">\r\n");
      out.write("                  <option value=\"201\">강남구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"202\">강동구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"203\">강북구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"204\">강서구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"205\">관악구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"206\">광진구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"207\">구로구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"208\">금천구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"209\">노원구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"210\">도봉구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"211\">동대문구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"212\">동작구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"213\">마포구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"214\">서대문구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"215\">서초구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"216\">성동구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"217\">성북구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"218\">송파구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"219\">양천구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"220\">영등포구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"221\">용산구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"222\">은평구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"223\">종로구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"224\">중구\r\n");
      out.write("                  </option>\r\n");
      out.write("                  <option value=\"225\">중랑구\r\n");
      out.write("                  </option>         \r\n");
      out.write("        </select>\r\n");
      out.write("        </div>\r\n");
      out.write("			<button type=\"submit\" id=\"signup\" style=\"margin-top:10px;\">계속</button>														\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>                     \r\n");
      out.write("   \r\n");
      out.write("   <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script> \r\n");
      out.write("       \r\n");
      out.write("   <script type =\"text/javascript\">\r\n");
      out.write("        $('#idchk').click(function(){\r\n");
      out.write("            let userId = $('#Idchecks').val(); // input_id에 입력되는 값            \r\n");
      out.write("            $.ajax({\r\n");
      out.write("               url : \"check.jsp\",\r\n");
      out.write("               type : \"post\",\r\n");
      out.write("               data : {userId: userId},\r\n");
      out.write("               dataType : 'json',\r\n");
      out.write("               success : function(result){\r\n");
      out.write("                if(result == 0){\r\n");
      out.write("                           $(\"#checkId\").html('사용할 수 없는 아이디입니다.');\r\n");
      out.write("                           $(\"#checkId\").attr('color','#dc3545');\r\n");
      out.write("                           $(\"#btnConfirm\").prop(\"disabled\",true);\r\n");
      out.write("                        }else{\r\n");
      out.write("                           $(\"#checkId\").html('사용할 수 있는 아이디입니다.');\r\n");
      out.write("                           $(\"#checkId\").attr('color','#2fb380');\r\n");
      out.write("                           $(\"#check\").val('idcheck');\r\n");
      out.write("                           $(\"#btnConfirm\").prop(\"disabled\",false);\r\n");
      out.write("                        } \r\n");
      out.write("                  },\r\n");
      out.write("                  error : function(){\r\n");
      out.write("                     lert(\"서버요청실패\");\r\n");
      out.write("                  }\r\n");
      out.write("            })             \r\n");
      out.write("        })\r\n");
      out.write("</script> \r\n");
      out.write("   \r\n");
      out.write("<script type =\"text/javascript\">\r\n");
      out.write("    $('#Mpb').click(function(){\r\n");
      out.write("           let userPh = $('#Mpv').val(); // input_id에 입력되는 값            \r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url : \"phCheck.jsp\",\r\n");
      out.write("            type : \"post\",\r\n");
      out.write("            data : {userPh: userPh},\r\n");
      out.write("            dataType : 'json',\r\n");
      out.write("            success : function(result){\r\n");
      out.write("                if(result == 0){\r\n");
      out.write("                    $(\"#Mpf\").html('사용할 수 없는 전화번호입니다.');\r\n");
      out.write("                    $(\"#Mpf\").attr('color','#dc3545');\r\n");
      out.write("                } else{\r\n");
      out.write("                    $(\"#Mpf\").html('사용할 수 있는 전화번호입니다.');\r\n");
      out.write("                    $(\"#Mpf\").attr('color','#2fb380');\r\n");
      out.write("                } \r\n");
      out.write("            },\r\n");
      out.write("            error : function(){\r\n");
      out.write("            alert(\"서버요청실패\");\r\n");
      out.write("            }\r\n");
      out.write("        })             \r\n");
      out.write("    })             \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type =\"text/javascript\">\r\n");
      out.write("        $('#emailchk').click(function(){\r\n");
      out.write("        let userEmail = $('#emailchkv').val(); // input_id에 입력되는 값            \r\n");
      out.write("           $.ajax({\r\n");
      out.write("              url : \"emailCheck.jsp\",\r\n");
      out.write("              type : \"post\",\r\n");
      out.write("              data : {userEmail: userEmail},\r\n");
      out.write("              dataType : 'json',\r\n");
      out.write("              success : function(result){\r\n");
      out.write("                 if(result == 0){\r\n");
      out.write("                          $(\"#emailft\").html('사용할 수 없는 이메일입니다.');\r\n");
      out.write("                          $(\"#emailft\").attr('color','#dc3545');\r\n");
      out.write("                          \r\n");
      out.write("                          \r\n");
      out.write("                        } else{\r\n");
      out.write("                           $(\"#emailft\").html('사용할 수 있는 이메일입니다.');\r\n");
      out.write("                           $(\"#emailft\").attr('color','#2fb380');\r\n");
      out.write("                        } \r\n");
      out.write("                 },\r\n");
      out.write("              error : function(){\r\n");
      out.write("                 alert(\"서버요청실패\");\r\n");
      out.write("              }\r\n");
      out.write("           })             \r\n");
      out.write("        })             \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type =\"text/javascript\">\r\n");
      out.write("        $('#kakaochk').click(function(){\r\n");
      out.write("        let userKakao = $('#kakaochkv').val(); // input_id에 입력되는 값            \r\n");
      out.write("           $.ajax({\r\n");
      out.write("              url : \"kakaoCheck.jsp\",\r\n");
      out.write("              type : \"post\",\r\n");
      out.write("              data : {userKakao: userKakao},\r\n");
      out.write("              dataType : 'json',\r\n");
      out.write("              success : function(result){\r\n");
      out.write("                 if(result == 0){\r\n");
      out.write("                          $(\"#kakaoft\").html('사용할 수 없는 카카오ID입니다.');\r\n");
      out.write("                          $(\"#kakaoft\").attr('color','#dc3545');\r\n");
      out.write("                          \r\n");
      out.write("                       \r\n");
      out.write("                        } else{\r\n");
      out.write("                           $(\"#kakaoft\").html('사용할 수 있는 카카오ID입니다.');\r\n");
      out.write("                           $(\"#kakaoft\").attr('color','#2fb380');                           \r\n");
      out.write("                        } \r\n");
      out.write("              },\r\n");
      out.write("              error : function(){\r\n");
      out.write("                 alert(\"서버요청실패\");\r\n");
      out.write("              }\r\n");
      out.write("           })             \r\n");
      out.write("        })             \r\n");
      out.write("</script>\r\n");
      out.write("<script src = \"js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("   $('.pw').keyup(function(){\r\n");
      out.write("       let pw1 = $(\"#ME_PASS\").val();\r\n");
      out.write("        let pw2 = $(\"#ME_PASS2\").val();\r\n");
      out.write("        \r\n");
      out.write("        if (pw1 != \"\" || pw2 != \"\"){\r\n");
      out.write("           if (pw1 == pw2){\r\n");
      out.write("               $(\"#checkPw\").html('비밀번호 일치');\r\n");
      out.write("               $(\"#checkPw\").attr('color','green');\r\n");
      out.write("            } else {\r\n");
      out.write("               $(\"#checkPw\").html('비밀번호 불일치');\r\n");
      out.write("                $(\"#checkPw\").attr('color','red');\r\n");
      out.write("            }\r\n");
      out.write("        }    \r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../Common/Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
