/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-03 03:40:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Footer include</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\r\n");
      out.write("		\r\n");
      out.write("<style>\r\n");
      out.write("	a{text-decoration: none;}\r\n");
      out.write("\r\n");
      out.write("</style> \r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"text-center text-lg-start bg-white text-muted\">\r\n");
      out.write("  <!-- Section: Social media -->\r\n");
      out.write("  <section class=\"d-flex justify-content-center justify-content-lg-between p-4 border-bottom\">\r\n");
      out.write("    <!-- Left -->\r\n");
      out.write("    <div class=\"me-5 d-none d-lg-block\">\r\n");
      out.write("      <span>Get connected with us on social networks:</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Left -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Right -->\r\n");
      out.write("    <div>\r\n");
      out.write("      <a href=\"\" class=\"me-4 link-secondary\">\r\n");
      out.write("        <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"\" class=\"me-4 link-secondary\">\r\n");
      out.write("        <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"\" class=\"me-4 link-secondary\">\r\n");
      out.write("        <i class=\"fab fa-google\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"\" class=\"me-4 link-secondary\">\r\n");
      out.write("        <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"\" class=\"me-4 link-secondary\">\r\n");
      out.write("        <i class=\"fab fa-linkedin\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"\" class=\"me-4 link-secondary\">\r\n");
      out.write("        <i class=\"fab fa-github\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Right -->\r\n");
      out.write("  </section>\r\n");
      out.write("  <!-- Section: Social media -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Section: Links  -->\r\n");
      out.write("  <section class=\"\">\r\n");
      out.write("    <div class=\"container text-center text-md-start mt-5\">\r\n");
      out.write("      <!-- Grid row -->\r\n");
      out.write("      <div class=\"row mt-3\">\r\n");
      out.write("        <!-- Grid column -->\r\n");
      out.write("        <div class=\"col-md-3 col-lg-4 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("          <!-- Content -->\r\n");
      out.write("          <h6 class=\"text-uppercase fw-bold mb-4\">\r\n");
      out.write("            <i class=\"fas fa-gem me-3 text-secondary\"></i>Company name\r\n");
      out.write("          </h6>\r\n");
      out.write("          <p>\r\n");
      out.write("            Here you can use rows and columns to organize your footer content. Lorem ipsum\r\n");
      out.write("            dolor sit amet, consectetur adipisicing elit.\r\n");
      out.write("          </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Grid column -->\r\n");
      out.write("        <div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("          <!-- Links -->\r\n");
      out.write("          <h6 class=\"text-uppercase fw-bold mb-4\">\r\n");
      out.write("            Products\r\n");
      out.write("          </h6>\r\n");
      out.write("          <p>\r\n");
      out.write("            <a href=\"#!\" class=\"text-reset\">Angular</a>\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <a href=\"#!\" class=\"text-reset\">React</a>\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <a href=\"#!\" class=\"text-reset\">Vue</a>\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <a href=\"#!\" class=\"text-reset\">Laravel</a>\r\n");
      out.write("          </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Grid column -->\r\n");
      out.write("        <div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("          <!-- Links -->\r\n");
      out.write("          <h6 class=\"text-uppercase fw-bold mb-4\">\r\n");
      out.write("            Useful links\r\n");
      out.write("          </h6>\r\n");
      out.write("          <p>\r\n");
      out.write("            <a href=\"#!\" class=\"text-reset\">Pricing</a>\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <a href=\"#!\" class=\"text-reset\">Settings</a>\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <a href=\"#!\" class=\"text-reset\">Orders</a>\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <a href=\"#!\" class=\"text-reset\">Help</a>\r\n");
      out.write("          </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Grid column -->\r\n");
      out.write("        <div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4\">\r\n");
      out.write("          <!-- Links -->\r\n");
      out.write("          <h6 class=\"text-uppercase fw-bold mb-4\">Contact</h6>\r\n");
      out.write("          <p><i class=\"fas fa-home me-3 text-secondary\"></i> 서울, NY 10012, US</p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <i class=\"fas fa-envelope me-3 text-secondary\"></i>\r\n");
      out.write("            info@example.com\r\n");
      out.write("          </p>\r\n");
      out.write("          <p><i class=\"fas fa-phone me-3 text-secondary\"></i> + 01 234 567 88</p>\r\n");
      out.write("          <p><i class=\"fas fa-print me-3 text-secondary\"></i> + 01 234 567 89</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Grid column -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Grid row -->\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <!-- Section: Links  -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("  <div class=\"text-center p-4\" style=\"background-color: rgba(0, 0, 0, 0.025);\">\r\n");
      out.write("    © 2021 Copyright:\r\n");
      out.write("    <a class=\"text-reset fw-bold\" href=\"https://mdbootstrap.com/\">MDBootstrap.com</a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
